### ISSUE TITLE
Fatal error: Uncought error: Class "BlockSDK\Base" not found.

### ISSUE THREAD

**Issue by sakawsar** [Block-Chen/blocksdk-php#1]
`include(plugin_dir_path( __FILE__ ).'vendor/autoload.php');`

Used the composer to get the repository and use the above line to attach it with my WordPress plugin file. But when I am going to activate my plugin it shows that issue.
![image](https://user-images.githubusercontent.com/9565536/87370686-74519200-c5a5-11ea-942d-b09edc2a3e2f.png)

**Comment by blockchen-admin** [comment]
namespace BlockSDK; Add to top line of blocksdk.php

use BlockSDK\BlockSDK;
$blockSDK = new BlockSDK("YOU_TOKEN");
$btcClient = $blockSDK->createBitcoin();
Please proceed with this code.

**Comment by sakawsar** [comment]
Okay let me check
