### ISSUE TITLE
Fatal error: Default value for parameters with a class type hint can only be NULL in D:\Server\htdocs\woo\wp-content\plugins\crypto-currency-payment-gateway\vendor\block-chen\blocksdk-php\src\base.php on line 8

### ISSUE THREAD

**Issue by sakawsar** [Block-Chen/blocksdk-php#2]
Which using `function __construct(string $api_token = ''){
			$this->api_token = $api_token;
		}` it is not working and showing like this.
![Capture](https://user-images.githubusercontent.com/9565536/87371032-50db1700-c5a6-11ea-9b1b-3675fc560ba0.JPG)

But when using `function __construct($api_token){
			$this->api_token = $api_token;
		}`  then it working fine.
Which one should I use.

**Comment by blockchen-admin** [comment]
The api_token value is not required and the bin character string must be passed to the default value.

**Comment by sakawsar** [comment]
Yes, you are right. But when using just the API key and below code, it shows the error.
```
use BlockSDK;
$blockSDK = new BlockSDK("YOU_TOKEN");
$btcClient = $blockSDK->createBitcoin();
```

**Comment by blockchen-admin** [comment]
What kind of error does it cause?

**Comment by sakawsar** [comment]
This kind of issue.
![](https://user-images.githubusercontent.com/9565536/87371032-50db1700-c5a6-11ea-9b1b-3675fc560ba0.JPG)

**Comment by sakawsar** [comment]
Moreover, I've added another [new issue](https://github.com/Block-Chen/blocksdk-php/issues/1). Would you please check?

**Comment by blockchen-admin** [comment]
namespace BlockSDK; Add to top line of blocksdk.php

use BlockSDK\BlockSDK;
$blockSDK = new BlockSDK("YOU_TOKEN");
$btcClient = $blockSDK->createBitcoin();
Please proceed with this code.

**Comment by sakawsar** [comment]
But I've used the static call method. What should I do in this case?

**Comment by blockchen-admin** [comment]
BlockSDK::createBitcoin("token")
Client static calls are supported.
However, method static call is not supported.
